// <auto-generated />
using System;
using API_Data.src.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API_Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260801052221_updateRelacionamentoTabela")]
    partial class updateRelacionamentoTabela
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API_Data.src.Model.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Atribuicao")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Atribuicao = 0,
                            Nome = "Moradia"
                        },
                        new
                        {
                            Id = 2,
                            Atribuicao = 0,
                            Nome = "Transporte"
                        },
                        new
                        {
                            Id = 3,
                            Atribuicao = 0,
                            Nome = "Alimentação"
                        },
                        new
                        {
                            Id = 4,
                            Atribuicao = 0,
                            Nome = "Lazer"
                        },
                        new
                        {
                            Id = 5,
                            Atribuicao = 0,
                            Nome = "Educação"
                        },
                        new
                        {
                            Id = 6,
                            Atribuicao = 0,
                            Nome = "Salário"
                        },
                        new
                        {
                            Id = 7,
                            Atribuicao = 0,
                            Nome = "Investimentos"
                        },
                        new
                        {
                            Id = 8,
                            Atribuicao = 0,
                            Nome = "Outros"
                        },
                        new
                        {
                            Id = 9,
                            Atribuicao = 0,
                            Nome = "Vale-Refeição"
                        },
                        new
                        {
                            Id = 10,
                            Atribuicao = 0,
                            Nome = "Vale-Transporte"
                        });
                });

            modelBuilder.Entity("API_Data.src.Model.ContaFixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("ContaFixa");
                });

            modelBuilder.Entity("API_Data.src.Model.ContaFixaParcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaFixaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorParcela")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaFixaId");

                    b.ToTable("contafixa_parcela", (string)null);
                });

            modelBuilder.Entity("API_Data.src.Model.Lancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("QtdParcelas")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Lancamentos");
                });

            modelBuilder.Entity("API_Data.src.Model.LancamentoParcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LancamentoId")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorParcela")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LancamentoId");

                    b.ToTable("lancamento_parcela", (string)null);
                });

            modelBuilder.Entity("API_Data.src.Model.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Casa"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Carro"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Gastos"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Mercado"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Energia"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Agua"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Internet"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Outros"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Facudade"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Emprestimo"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Streaming"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "IA"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Armazenamento em Nuvem"
                        });
                });

            modelBuilder.Entity("ContaFixaTag", b =>
                {
                    b.Property<int>("ContasFixasId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("ContasFixasId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ContaFixaTags", (string)null);
                });

            modelBuilder.Entity("LancamentoTag", b =>
                {
                    b.Property<int>("LancamentosId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("LancamentosId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("LancamentoTags", (string)null);
                });

            modelBuilder.Entity("API_Data.src.Model.ContaFixa", b =>
                {
                    b.HasOne("API_Data.src.Model.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("API_Data.src.Model.ContaFixaParcela", b =>
                {
                    b.HasOne("API_Data.src.Model.ContaFixa", "ContaFixa")
                        .WithMany("Parcelas")
                        .HasForeignKey("ContaFixaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaFixa");
                });

            modelBuilder.Entity("API_Data.src.Model.Lancamento", b =>
                {
                    b.HasOne("API_Data.src.Model.Categoria", "Categoria")
                        .WithMany("Lancamentos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("API_Data.src.Model.LancamentoParcela", b =>
                {
                    b.HasOne("API_Data.src.Model.Lancamento", "Lancamento")
                        .WithMany("Parcelas")
                        .HasForeignKey("LancamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lancamento");
                });

            modelBuilder.Entity("ContaFixaTag", b =>
                {
                    b.HasOne("API_Data.src.Model.ContaFixa", null)
                        .WithMany()
                        .HasForeignKey("ContasFixasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Data.src.Model.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LancamentoTag", b =>
                {
                    b.HasOne("API_Data.src.Model.Lancamento", null)
                        .WithMany()
                        .HasForeignKey("LancamentosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Data.src.Model.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API_Data.src.Model.Categoria", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("API_Data.src.Model.ContaFixa", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("API_Data.src.Model.Lancamento", b =>
                {
                    b.Navigation("Parcelas");
                });
#pragma warning restore 612, 618
        }
    }
}
