// <auto-generated />
using System;
using API_Data.src.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API_Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812001941_UpdateTabelaModel")]
    partial class UpdateTabelaModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API_Data.src.Model.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Atribuicao")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Nome")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("API_Data.src.Model.ContaFixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UserId");

                    b.ToTable("ContaFixa");
                });

            modelBuilder.Entity("API_Data.src.Model.ContaFixaParcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaFixaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorParcela")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaFixaId");

                    b.HasIndex("Status", "DataVencimento", "ContaFixaId")
                        .HasDatabaseName("IX_ContaFixaParcela_Status_DataVencimento_ContaFixa");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status", "DataVencimento", "ContaFixaId"), new[] { "ValorParcela" });

                    b.ToTable("contafixa_parcela", (string)null);
                });

            modelBuilder.Entity("API_Data.src.Model.HistoricoFinanceiroAnual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalDivida")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalSaldo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Ano", "Mes")
                        .IsUnique();

                    b.ToTable("HistoricosFinanceiros");
                });

            modelBuilder.Entity("API_Data.src.Model.Lancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("QtdParcelas")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UserId");

                    b.ToTable("Lancamentos");
                });

            modelBuilder.Entity("API_Data.src.Model.LancamentoParcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LancamentoId")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorParcela")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LancamentoId");

                    b.HasIndex("Status", "DataVencimento", "LancamentoId")
                        .HasDatabaseName("IX_LancamentoParcela_Status_DataVencimento_Lancamento");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status", "DataVencimento", "LancamentoId"), new[] { "ValorParcela" });

                    b.ToTable("lancamento_parcela", (string)null);
                });

            modelBuilder.Entity("API_Data.src.Model.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Nome")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("API_Data.src.Model.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ContaFixaTag", b =>
                {
                    b.Property<int>("ContasFixasId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("ContasFixasId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ContaFixaTags", (string)null);
                });

            modelBuilder.Entity("LancamentoTag", b =>
                {
                    b.Property<int>("LancamentosId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("LancamentosId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("LancamentoTags", (string)null);
                });

            modelBuilder.Entity("API_Data.src.Model.Categoria", b =>
                {
                    b.HasOne("API_Data.src.Model.User", "User")
                        .WithMany("Categorias")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("API_Data.src.Model.ContaFixa", b =>
                {
                    b.HasOne("API_Data.src.Model.Categoria", "Categoria")
                        .WithMany("ContasFixas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_Data.src.Model.User", "User")
                        .WithMany("ContasFixas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API_Data.src.Model.ContaFixaParcela", b =>
                {
                    b.HasOne("API_Data.src.Model.ContaFixa", "ContaFixa")
                        .WithMany("Parcelas")
                        .HasForeignKey("ContaFixaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaFixa");
                });

            modelBuilder.Entity("API_Data.src.Model.HistoricoFinanceiroAnual", b =>
                {
                    b.HasOne("API_Data.src.Model.User", "User")
                        .WithMany("HistoricosFinanceiros")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("API_Data.src.Model.Lancamento", b =>
                {
                    b.HasOne("API_Data.src.Model.Categoria", "Categoria")
                        .WithMany("Lancamentos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_Data.src.Model.User", "User")
                        .WithMany("Lancamentos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API_Data.src.Model.LancamentoParcela", b =>
                {
                    b.HasOne("API_Data.src.Model.Lancamento", "Lancamento")
                        .WithMany("Parcelas")
                        .HasForeignKey("LancamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lancamento");
                });

            modelBuilder.Entity("API_Data.src.Model.Tag", b =>
                {
                    b.HasOne("API_Data.src.Model.User", "User")
                        .WithMany("Tags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContaFixaTag", b =>
                {
                    b.HasOne("API_Data.src.Model.ContaFixa", null)
                        .WithMany()
                        .HasForeignKey("ContasFixasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Data.src.Model.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LancamentoTag", b =>
                {
                    b.HasOne("API_Data.src.Model.Lancamento", null)
                        .WithMany()
                        .HasForeignKey("LancamentosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Data.src.Model.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API_Data.src.Model.Categoria", b =>
                {
                    b.Navigation("ContasFixas");

                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("API_Data.src.Model.ContaFixa", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("API_Data.src.Model.Lancamento", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("API_Data.src.Model.User", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("ContasFixas");

                    b.Navigation("HistoricosFinanceiros");

                    b.Navigation("Lancamentos");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
